[project]
name = "osdag"
version = "2026.02.0.0"
description = "Osdag-Open Steel Design and Graphics"
authors = ["Osdag Team"]
channels = ["conda-forge", "osdag"]
platforms = ["win-64"]

[dependencies]
osdag = "==2026.02.0.0"
python = ">=3.11,<=3.13"
numpy = "==2.4.2"
openpyxl = "==3.1.5"
pandas = "==3.0.0"
pylatex = "==1.4.2"
pyside6 = "==6.9.2"
markdown = "==3.10.1"
osdag_latex_env = "==1.0.2"
pythonocc-core = "==7.9.0"
click = "==8.3.1"
pyyaml = "==6.0.3"
smesh = "==9.9.0.0"
sqlite = "==3.51.2"
tbb = "==2022.3.0"

[tasks]
run = "osdag"
