[project]
name = "osdag"
version = "2026.02.0.0"
description = "Osdag-Open Steel Design and Graphics"
authors = ["Osdag Team"]
channels = ["conda-forge", "osdag"]
platforms = ["win-64"]

[dependencies]
osdag = "==2026.02.0.0"
python = ">=3.11,<=3.13"

[tasks]
run = "osdag"
